[versions]
minecraft = "1.20.2"
quilt_mappings = "1.20.2+build.2"
fabric_loader = "0.14.22"
fabric_api = "0.89.2+1.20.2"
midnightlib = "1.5.0-fabric"
modmenu = "8.0.0"

fabric_loom = "1.3-SNAPSHOT"
loom_quiltflower = "1.6.0"
publishing = "0.3.5"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
midnightlib = { module = "maven.modrinth:midnightlib", version.ref = "midnightlib" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]

[plugins]
#     id "me.modmuss50.mod-publish-plugin" version "0.3.5"
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
loom_quiltflower = { id = "io.github.juuxel.loom-quiltflower", version.ref = "loom_quiltflower" }
publishing = { id = "me.modmuss50.mod-publish-plugin", version.ref = "publishing" }
